### ISSUE TITLE
More then one ACF Gallery in Post 

### ISSUE THREAD

**Issue by Karuma** [magicstickuk/multisite-post-duplicator#49]
Hi ^^
If you have more than one field of the Gallery, interesting things happen. I do not know how to describe it exactly, I will show the final result.
Original :
![2017-12-05 1](https://user-images.githubusercontent.com/4147997/33633743-2c1cfe92-da12-11e7-8459-c6f121938a7f.png)
Copy : 
![2017-12-05 2](https://user-images.githubusercontent.com/4147997/33633750-2fc336a6-da12-11e7-9c5d-22e0b67e804a.png)

**Comment by WillyMichel** [comment]
@Karuma Hi ! I found the problem and the solution.
In the file `acf-functions.php` at the line 252 you have `$attach_ids = array();`. This must be inside the first following `foreach`. Just move line 252 to the 254th line.

**Comment by magicstickuk** [comment]
Thanks for this. fix will go out with version 1.7.6 in a few days.
