### ISSUE TITLE
Problem with ACF fields group registered in PHP

### ISSUE THREAD

**Issue by WillyMichel** [magicstickuk/multisite-post-duplicator#52]
Hello,

There's a big problem when you register your ACF fields with PHP. Well... it's a guess.
When duplicating a post with ACF fields of image type it does not copy the images. I debugged it and found that in your function `mpd_do_acf_images_from_source` you check the ACF field type with a query to search in the `wp_posts` table. But when you register ACF field with PHP there are no acf-field post_type in this table, so your function never process the acf fields image, file and gallery.
You should do a fix to handle this.

Thanks

**Comment by magicstickuk** [comment]
Fixed as part of your pull request #53 Thank you!
